In [1]:
import pandas as pd
import numpy as np
print("DataFrame.apply function:\n")
info = pd.DataFrame ([[3, 9]]*4 , columns =['S' ,'R'])
print("\nOriginal DataFrame:\n", info)
print("\nSquare root of DataFrame:\n", info.apply(np.sqrt))
print("\nSum of each column:\n", info.apply(np.sum, axis=0))
print("\nSum of each row:\n", info.apply(np.sum,axis=1))


info=pd.DataFrame([[2,4,6],[1,3,5],[5,8,7]],columns =['X','Y','Z'])
print("\nOriginal DataFrame:\n", info)
print("\nMinimum and Maximum of each column: \n")
print(info.agg(['min','max']))


print("\nDataFrame.Assign function:\n")
d2 = pd.DataFrame([['Sheik',88], ['Prthzz',70]], columns=['Emp','ID'])
print("\nOriginal DataFrame:\n",d2)
d2['Age']=[20,18]
print("\nAdding new column:\n",d2)
d=d2.assign(Sex=['Male','Female'])
print("\nAdding new column:\n",d)


print("\nDataFrame Sort function:\n")
info=pd.DataFrame(np.random.randn(5,2),index=[3,2,0,4,1],columns=['col3','col4'])
print(info)
info2=info.sort_index()
print("\nSort index:\n",info2)
#info = pd.DataFrame({'col3':[7,1,8,3],'col4':[8,12,4,9]})
info3 = info.sort_values(by='col3')
print("\nSort Values:\n",info3)



print("\nDataFrame.Merge function:\n")
left=pd.DataFrame({'id': [1,2,3,4],
                    'Name': ['Sheik', 'prthzz', 'Abu', 'Vishwa'],
                    'sub': ['sub1', 'sub2', 'sub4','sub3']})

right=pd.DataFrame({
                    'id':[1,2,3,4],
                    'Name': ['Nishanth', 'Maanesh', 'Som', 'sooriya'],
                    'sub':['sub2', 'sub4', 'sub3', 'sub5']})
print(left)
print(right)
print(pd.merge(left,right,on="id"))

DataFrame.apply function:


Original DataFrame:
    S  R
0  3  9
1  3  9
2  3  9
3  3  9

Square root of DataFrame:
           S    R
0  1.732051  3.0
1  1.732051  3.0
2  1.732051  3.0
3  1.732051  3.0

Sum of each column:
 S    12
R    36
dtype: int64

Sum of each row:
 0    12
1    12
2    12
3    12
dtype: int64

Original DataFrame:
    X  Y  Z
0  2  4  6
1  1  3  5
2  5  8  7

Minimum and Maximum of each column:

     X  Y  Z
min  1  3  5
max  5  8  7

DataFrame.Assign function:


Original DataFrame:
       Emp  ID
0   Sheik  88
1  Prthzz  70

Adding new column:
       Emp  ID  Age
0   Sheik  88   20
1  Prthzz  70   18

Adding new column:
       Emp  ID  Age     Sex
0   Sheik  88   20    Male
1  Prthzz  70   18  Female

DataFrame Sort function:

       col3      col4
3 -0.057301  0.433775
2  0.839235  0.700248
0  0.527998  0.356810
4  1.401321  0.531830
1  1.087141 -0.396895

Sort index:
        col3      col4
0  0.527998  0.356810
1  1.087141 -0.396895
2  0.839235  0.700248
3 -0.057301  0.433775
4  1.401321  0.531830

Sort Values:
        col3      col4
3 -0.057301  0.433775
0  0.527998  0.356810
2  0.839235  0.700248
1  1.087141 -0.396895
4  1.401321  0.531830

DataFrame.Merge function:

   id    Name   sub
0   1   Sheik  sub1
1   2  prthzz  sub2
2   3     Abu  sub4
3   4  Vishwa  sub3
   id      Name   sub
0   1  Nishanth  sub2
1   2   Maanesh  sub4
2   3       Som  sub3
3   4   sooriya  sub5
   id  Name_x sub_x    Name_y sub_y
0   1   Sheik  sub1  Nishanth  sub2
1   2  prthzz  sub2   Maanesh  sub4
2   3     Abu  sub4       Som  sub3
3   4  Vishwa  sub3   sooriya  sub5