In [1]:
import pandas as hah
df=hah.DataFrame()
print(df)

import pandas as hah
emp=hah.Series(['Ajith','Jack','Rose','Yatra','Maaraa'])
id=hah.Series([80,90,28,57,49])
frame={'Emp':emp,'ID':id}
result=hah.DataFrame(frame)
print("\nSeries to Data Frame\n")
print(result)

print("\nExtracting one column:\n")
print(result['Emp'])

print("\nAdding new column:\n")
result['ID']=hah.Series([80,90,28,56,89])
result['Age']=hah.Series([19,90,34,67,20])
print(result)

print("\nDeleting new column:\n")
del result['Age']
print(result)

print("\nExtracting the second row:\n")
print(result.loc[1])

print("Slice rows:\n",result[1:4])

d2=hah.DataFrame([['Vicky',100],['Rashid',109]],columns=['Emp','ID'])
print("\nAdding new row values:\n",result.append(d2))

print("\nDeleting particular row:\n",result.drop(2))

Empty DataFrame
Columns: []
Index: []

Series to Data Frame

      Emp  ID
0   Ajith  80
1    Jack  90
2    Rose  28
3   Yatra  57
4  Maaraa  49

Extracting one column:

0     Ajith
1      Jack
2      Rose
3     Yatra
4    Maaraa
Name: Emp, dtype: object

Adding new column:

      Emp  ID  Age
0   Ajith  80   19
1    Jack  90   90
2    Rose  28   34
3   Yatra  56   67
4  Maaraa  89   20

Deleting new column:

      Emp  ID
0   Ajith  80
1    Jack  90
2    Rose  28
3   Yatra  56
4  Maaraa  89

Extracting the second row:

Emp    Jack
ID       90
Name: 1, dtype: object
Slice rows:
      Emp  ID
1   Jack  90
2   Rose  28
3  Yatra  56

Adding new row values:
       Emp   ID
0   Ajith   80
1    Jack   90
2    Rose   28
3   Yatra   56
4  Maaraa   89
0   Vicky  100
1  Rashid  109

Deleting particular row:
       Emp  ID
0   Ajith  80
1    Jack  90
3   Yatra  56
4  Maaraa  89

C:\Users\Tcs\AppData\Local\Temp\ipykernel_27428\2123395490.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print("\nAdding new row values:\n",result.append(d2))